require: 'rubocop-rspec'

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 10

RSpec/ImplicitExpect:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 8

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedExample:
  Enabled: false
